# Generated by Django 5.1.3 on 2024-11-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_course_owner_lesson_owner_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("id",),
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("id",),
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
